<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="myrobot">

	<xacro:property name="width" value="0.02"/>
	<xacro:property name="width_1" value="0.01"/>
	<xacro:property name="body_len" value="0.2"/>
	<xacro:property name="box_param" value="0.5"/>
	<xacro:property name="spawn_point" value="3"/>
	<xacro:property name="radius" value="0.1"/>

		<!-- REFERENCE FRAME/CHILD/PARENT http://wiki.ros.org/urdf/XML/joint/-->
		<!-- SDF documentation: http://sdformat.org/ -->
		<!-- xacro(XML macro): http://wiki.ros.org/xacro -->
		<!-- URDF in GAZEBO: http://gazebosim.org/tutorials/?tut=ros_urdf#%3Cgazebo%3Eelementforthetag -->
		<!-- URDF tutorials:http://wiki.ros.org/urdf/Tutorials -->
		<!-- Gravity disable: http://answers.gazebosim.org/question/13416/how-to-disable-gravity-only-for-a-specific-model-in-gazebo/ -->
		<!-- WORLD_TO_BASE fixed joint - TF between base and world -->
		<!-- NEXT_STEPS NEXT_STEPS NEXT_STEPS -->
		<!-- BASE_TO_ROPE1 link is ofsetted for -box_param/2 so it could be connected on bottom of the base, while visual properties
			of link rope_1 are offseted by -body_len/2 so we could connect it on the bottom of  the base and have full link at disposal-->
		<!-- CREATE BALL LINK - series of revolute joints or infitensimaly small links connected with simple revolute/continuous joints-->
		<!-- PHYSICS THE ROPE, INERTIA ELEMENTS FOR ROPE AND LOAD SHOULD BE CALCULATED -->
		<!-- XACRO PROPERTIES, LAUNCH FILE AUTOMATICALLY CONVERTS XACRO TO URDF -->
		

		<link name="world"/>	
		
		<link name="base_link">			
			<visual>
				<geometry>	
					<box size="${box_param} ${box_param} ${box_param}"/>										
				</geometry>					
			</visual>

			<collision>
				<geometry>
					<box size="${box_param} ${box_param} ${box_param}"/>						
				</geometry>
			</collision>

			<inertial>
			<mass value="0.01"/>
			<inertia 
				ixx="0.01" ixy="0.0" ixz="0.0"
        		iyy="0.01" iyz="0.0"
        		izz="0.01"/>
			</inertial>
		</link>		
		

		<link name="rope_1">
			<visual>
				<geometry>	
					<cylinder radius="${width}" length="${body_len}"/>						
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>-
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${width}" length="${body_len}"/>
				</geometry>
				<origin xyz="0  0 ${-body_len/2}" rpy="0 0 0"/>
			</collision>
				
			<inertial>
			<mass value="0.01"/>
			<inertia 
				ixx="0.01" ixy="0.0" ixz="0.0"
        		iyy="0.01" iyz="0.0"
        		izz="0.01"/>
			</inertial>
		</link>

		<link name="rope_2">
			<visual>
				<geometry>	
					<cylinder radius="${width_1}" length="${body_len}"/>						
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
				<material name="red"/>		
			</visual>
			<collision>
				<geometry>
					<cylinder radius="${width_1}" length="${body_len}"/>
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>-->
			</collision>
				
			<inertial>
				<mass value="0.01"/>
				<inertia 
					ixx="0.01" ixy="0.0" ixz="0.0"
        			iyy="0.01" iyz="0.0"
        			izz="0.01"/>
			</inertial>
		</link>

		<link name="rope_3">
			<visual>	
				<geometry>
					<cylinder radius="${width_1}" length="${body_len}"/>
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
			</visual>	
			<collision>
				<geometry>
					<cylinder radius="${width_1}" length="${body_len}"/>
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
			</collision>

			<inertial>
				<mass value="0.01"/>

				<inertia 
					ixx="0.01" ixy="0.0" ixz="0.0"
        			iyy="0.01" iyz="0.0"
        			izz="0.01"/>
			</inertial>
		</link>

		<link name="rope_4">
			<visual>	
				<geometry>
					<cylinder radius="${width_1}" length="${body_len}"/>
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
			</visual>	
			<collision>
				<geometry>
					<cylinder radius="${width_1}" length="${body_len}"/>
				</geometry>
				<origin xyz="0 0 ${-body_len/2}" rpy="0 0 0"/>
			</collision>

			<inertial>
				<mass value="0.01"/>

				<inertia 
					ixx="0.01" ixy="0.0" ixz="0.0"
        			iyy="0.01" iyz="0.0"
        			izz="0.01"/>
			</inertial>
		</link>

		<link name="load">
			<visual>
				<geometry>
					<sphere radius="${radius}"/>
				</geometry>
				<origin xyz="0 0 ${-radius/2}" rpy="0 0 0"/>
			</visual>

			<collision>
				<geometry>
					<sphere radius="${radius}"/>
				</geometry>
				<origin xyz="0 0 ${-radius/2}" rpy="0 0 0"/>
			</collision>

			<inertial>
				<mass value="0.1"/>
				<inertia
					ixx="0.1" ixy="0.0" ixz="0.0"
					iyy="0.1" iyz="0.0"
					izz="0.1"/>
			</inertial>
		</link>
			
		<joint name="world_to_base_link" type="fixed">
				<parent link="world"/>
				<child link="base_link"/>
				<origin xyz="0 0 ${spawn_point}"/>

		</joint>


		<joint name="base_linktorope1" type="revolute">
    		<parent link="base_link"/>
    		<child link="rope_1"/>
    		<origin xyz="0 0 ${-box_param/2}"/>
			<axis xyz="0 1 0"/>
			<limit lower="-1.5707" upper="1.5707" effort="0.01" velocity="0.01"/>
		</joint>

		<joint name="rope1_to_rope2" type="revolute">
			<parent link="rope_1"/>
			<child link="rope_2"/>
			<origin xyz="0 0 ${-body_len}"/>
			<axis xyz="0 1 0" />
			<limit lower="-1.5707" upper="1.5707" effort="0.01" velocity="0.01"/>
		</joint>

		<joint name="rope2_to_rope3" type="revolute">
			<parent link="rope_2"/>
			<child link="rope_3"/>
			<origin xyz="0 0 ${-body_len}"/>
			<axis xyz="1 0 0"/>
			<limit lower="-1.5707" upper="1.5707" effort="0.01" velocity="0.01"/>
		</joint>

		<joint name="rope3_to_rope4" type="revolute">
			<parent link="rope_3"/>
			<child link="rope_4"/>
			<origin xyz="0 0 ${-body_len}"/>
			<axis xyz="0 1 0"/>
			<limit lower="-1.5707" upper="1.5707" effort="0.01" velocity="0.01"/>
		</joint>
		

		<joint name="rope4_to_load" type="revolute">
			<parent link="rope_4"/>
			<child link="load"/>
			<origin xyz="0 0 ${-body_len}"/>
			<axis xyz="0 1 0"/>
			<limit lower="-1.5707" upper="1.5707" effort="0.01" velocity="0.01"/>
		</joint>
		
		<gazebo reference="rope_1">
			<material>Gazebo/Blue</material>
		</gazebo>
		<gazebo reference="rope_2">
			<material>Gazebo/Green</material>
		</gazebo>
		<gazebo reference="rope_3">
			<material>Gazebo/Blue</material>
		</gazebo>
		<gazebo reference="rope_4">
			<material>Gazebo/Green</material>
		</gazebo>
		<gazebo reference="load">
			<material>Gazebo/Red</material>
		</gazebo>
		<gazebo reference="base_link">
			<static>1</static>
			<gravity>0</gravity>
		</gazebo>

</robot>
							

